name: Update Investing Calendar

on:
  schedule:
    - cron: '0 21 * * *'  # Every day at 21:00 UTC
    # - cron: '0 4 * * *'  # Every day at 04:00 UTC
    # - cron: '0 */6 * * *'  # Every 6 hours
    # - cron: '0 * * * *'  # Every hour
    # - cron: '30 2 * * *'  # Every day at 02:30 UTC
    # - cron: '0 12 * * 1-5'  # Weekdays only at 12:00 UTC
    # - cron: '0 0 * * *'  # Every day at 00:00 UTC
  workflow_dispatch:

jobs:
  scrape-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install --with-deps

      - name: Run news scraper
        run: python investing_news_scraper.py

      - name: Commit and push updated news_schedule.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add news_schedule.json || true
          git commit -m "🗓 Auto-update news_schedule.json" || true
          git push || true
