# .github/workflows/update-calendar.yml
name: Update Investing Calendar

on:
  schedule:
    - cron: '0 6 * * *'  # Every day at 6:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run news scraper
        run: python investing_news_scraper.py

      - name: Commit and push news_schedule.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add news_schedule.json
          git commit -m "🔄 Update news_schedule.json from Investing.com" || echo "No changes to commit"
          git push
